#!/bin/bash

BASEDIR=$(readlink -f $0 | xargs dirname)

ln -s $BASEDIR/tmux.conf $HOME/.tmux.conf
ln -s $BASEDIR/vimrc $HOME/.vimrc

# prezto
if [ -d $BASEDIR/zsh/prezto ]; then

cd $BASEDIR/zsh/prezto
git pull && git submodule update --init --recursive
cd $BASEDIR

ln -s $BASEDIR/zsh/prezto $HOME/.zprezto

ln -s $HOME/.zprezto/runcoms/zlogin $HOME/.zlogin
ln -s $HOME/.zprezto/runcoms/zlogout $HOME/.zlogout
ln -s $HOME/.zprezto/runcoms/zprofile $HOME/.zprofile
ln -s $HOME/.zprezto/runcoms/zshenv $HOME/.zshenv
ln -s $HOME/.zprezto/runcoms/zshrc $HOME/.zshrc
ln -s $BASEDIR/zsh/zpreztorc $HOME/.zpreztorc

echo "export DOTFILES=$BASEDIR" >> $HOME/.zshrc

for f in $(ls -f $BASEDIR/zsh/*.zsh); do
    echo "source $f" >> $HOME/.zshrc
done

cat >> $HOME/.zshrc << EOF
if [ -f "${ZDOTDIR:-$HOME}/.zsh_local" ]; then
    source "${ZDOTDIR:-$HOME}/.zsh_local"  
fi 
EOF

fi
