#!/usr/bin/env bash

BASEDIR=$(readlink -f $0 | xargs dirname)

# tmux
[[ -f "$HOME/.tmux.conf" ]] && mv "$HOME/.tmux.conf" "$HOME/.tmux.conf.orig"
ln -s $BASEDIR/tmux.conf $HOME/.tmux.conf

# vim
[[ -f "$HOME/.vimrc" ]] && mv "$HOME/.vimrc" "$HOME/.vimrc.orig"
[[ -d "$HOME/.vim" ]] && mv "$HOME/.vim" "$HOME/.vim.orig"
ln -s $BASEDIR/vimrc $HOME/.vimrc

# prezto

zfiles=(".zlogin" ".zlogout" ".zprofile" ".zshenv" ".zshrc" ".zpreztorc")
for zfile in ${zfiles[*]}; do
    [[ -f "$HOME/$zfile" ]] && mv "$HOME/$zfile" "$HOME/$zfile.orig"
done
[[ -d "$HOME/.zprezto" ]] && mv "$HOME/.zprezto" "$HOME/.zprezto.orig"

if [ -d $BASEDIR/zsh/prezto ]; then

cd $BASEDIR/zsh/prezto
git pull && git submodule update --init --recursive
cd $BASEDIR

ln -s $BASEDIR/zsh/prezto $HOME/.zprezto

ln -s $HOME/.zprezto/runcoms/zlogin $HOME/.zlogin
ln -s $HOME/.zprezto/runcoms/zlogout $HOME/.zlogout
ln -s $HOME/.zprezto/runcoms/zprofile $HOME/.zprofile
ln -s $HOME/.zprezto/runcoms/zshenv $HOME/.zshenv
ln -s $HOME/.zprezto/runcoms/zshrc $HOME/.zshrc
ln -s $BASEDIR/zsh/zpreztorc $HOME/.zpreztorc

echo "export DOTFILES=$BASEDIR" >> $HOME/.zshrc

for f in $(ls -f $BASEDIR/zsh/*.zsh); do
    echo "source $f" >> $HOME/.zshrc
done

cat >> $HOME/.zshrc << EOF

# Include custom config
[[ -f "$HOME/.zsh.local"  ]] && source "$HOME/.zsh.local"
EOF

fi
