#!/bin/bash

FILE=$(readlink -f "$0")
DOTFILES_PATH=$(dirname "$FILE")

ln -s $DOTFILES_PATH/tmux.conf $HOME/.tmux.conf
ln -s $DOTFILES_PATH/vimrc $HOME/.vimrc

# prezto
if [ -d $DOTFILES_PATH/zsh/prezto ];
then
cd $DOTFILES_PATH/zsh/prezto
git pull && git submodule update --init --recursive
cd $DOTFILES_PATH

ln -s $DOTFILES_PATH/zsh/prezto $HOME/.zprezto

ln -s $HOME/.zprezto/runcoms/zlogin $HOME/.zlogin
ln -s $HOME/.zprezto/runcoms/zlogout $HOME/.zlogout
ln -s $HOME/.zprezto/runcoms/zprofile $HOME/.zprofile
ln -s $HOME/.zprezto/runcoms/zshenv $HOME/.zshenv
ln -s $HOME/.zprezto/runcoms/zshrc $HOME/.zshrc
ln -s $DOTFILES_PATH/zsh/zpreztorc $HOME/.zpreztorc

fi
